eureka:
  client:
    serviceUrl:
      #defaultZone: http://192.168.140.141:8766/eureka/
      defaultZone: http://localhost:8766/eureka/
server:
  port: 8004
spring:
  application:
    name: springtest
